[build]
  publish = "build"
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[plugins]]
  package = "@netlify/plugin-pnpm"

# Uncomment the following if you need to install specific pnpm version
# [build.environment]
# PNPM_VERSION = "8.6.2"
